### ISSUE TITLE
Conflict with FS22_A_ProductionRevamp

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Frvetz/FS22_RealisticDamageSystem#1]
Hello. There is such a problem: If I am in a car and call the production menu, I want to buy resources for him (this is a mod ProductionRevamp) half of the text from mod ProductionRevamp, and the second half from your mod.

**Comment by Gonimy-Vetrom** [comment]
![fsScreen_2023_12_24_20_18_48](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/8200153/40f9dddf-e7f2-4f37-b091-84f0b83a71e2)

**Comment by Gonimy-Vetrom** [comment]
oops. It turns out that it was necessary to translate other files. It turns out that it was necessary to translate other files.

**Comment by Frvetz** [comment]
Oh hahahah thank you! I know why 😄 I'll fix it soon

**Comment by Frvetz** [comment]
Fixed version is online 😉 Turned out to be a pretty heavy bug actually thanks for noticing
