### ISSUE TITLE
Damage even when the appliance is stationary

### ISSUE THREAD

**Issue by 0scarZulu** [Frvetz/FS22_RealisticDamageSystem#11]
Hello, 

First of all, thank you very much for the great expansion of the damage system. However, I have now noticed something that somehow doesn't appeal to me. That the machines get damage even when they are stationary. 
For example, if I wait for my thresher to finish harvesting and then put it in the shed until the next year, it has been damaged. Is that intentional? Can't this be linked somehow to the operating hours? In other words, does the damage occur with increasing operating hours and not when it is not being used? 

Thank you very much
Cheers

**Comment by Frvetz** [comment]
Hello,

thank you very much! This is indeed intentional yes. Just like in reallife your vehicle gets damages when it is used but also when it is not used. 

The script uses the operating hour and the age of a vehicle to determine when a damage should occur.

Hope this helps
Cheers
