### ISSUE TITLE
Pallet moving alone

### ISSUE THREAD

**Issue by bibifr** [Frvetz/FS22_RealisticDamageSystem#18]
Hello, 
for some reason when i driving courseplay whit harvester near the pallet, this one start to move alone arround the map. 
Something i noticed whit old and this version. 

Maybe could you check it ?

Best regard

**Comment by Frvetz** [comment]
I'll take a look at it. Thank you for reporting it!

**Comment by Frvetz** [comment]
Fixed! Thank you very much for reporting the issue!
