### ISSUE TITLE
Schäden nach ReLogin auf Server wieder vorhanden

### ISSUE THREAD

**Issue by Nordlicht-76** [Frvetz/FS22_RealisticDamageSystem#20]
Moin,

wenn ich auf dem Server spiele und dort eine Reparatur abgeschlossen habe, tauchen die Schäden nach dem nächsten ReLogin wieder auf.

- Abschluß der Reparatur normal, oder über Konsole mit remove, reset oder stop (6 Schäden )
- 0 Schäden vorhanden
- Fahrzeug bewegt
- Spiel speichern
- Ausloggen
- etwas warten
- neu einloggen
- Fahrzeug steht an der neuen Stelle, zeigt aber wieder die 6 Schäden an

Dann habe ich mir das Savegame genommen und lokal probiert. Spiel gespeichert, Game beendet und lokal neu gestartet.
Hier wurden die Schäden nicht wieder angezeigt und blieben auf 0.

Server ist so eingestellt, daß er pausiert, wenn kein Player online ist.

Gruß
André

**Comment by Frvetz** [comment]
Moin moin,

Danke dir für's Melden! Schaue ich mir an!

Grüße
Gerrit / frvetz

**Comment by Frvetz** [comment]
Könntest du noch so freundlich sein und mir hier deine Log + Server Log zu schicken nachdem der Fehler aufgetreten ist?

Du findest deine Log hier: 
Dokumente -> My Games -> Farming Simulator 22 -> log.txt

**Comment by Nordlicht-76** [comment]
> Könntest du noch so freundlich sein und mir hier deine Log + Server Log zu schicken nachdem der Fehler aufgetreten ist?
> 
> Du findest deine Log hier: Dokumente -> My Games -> Farming Simulator 22 -> log.txt

Mache ich Dir gerade fertig. Bin am reproduzieren unter unterschiedlichen Bedingungen und mit weniger Mods um hier auch ein wenig auszuschliessen bzw. evtl. einen zu finden der jetzt inkompatibel ist.

**Comment by Nordlicht-76** [comment]
[Client_BasicMod.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14323617/Client_BasicMod.txt)
[Server_BasicMod.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14323618/Server_BasicMod.txt)
Es ließ sich auch mit weniger Mods reproduzieren, deshalb nur die Log's mit weniger Mods ;)

Interessanterweise ist mir beim Reproduzieren noch folgendes aufgefallen:
Direkt nach Server-Neustart Schäden über die Konsole entfernt. Dann Traktor gestartet und sachte 10m gefahren. Plötzlich waren die Schäden wieder da. evtl ein Zusammenhang mit CVT? Motor war noch kalt, aber laut CVT soll sachte bewegen im kalten Zustand nix ausmachen.
Dennoch Schäden wieder entfernt, logout, login, Schäden vorhanden.

Die Log's bilden die gesamte Prozedur ab.

**Comment by Frvetz** [comment]
Danke dir!

Noch eine Frage... Das ganze passiert auch, wenn man das Fahrzeug normal mit der Palette repariert und nicht über die Befehle richtig?

**Comment by Nordlicht-76** [comment]
Ja, dadurch ist es mir aufgefallen. Gerade ne Reparatur fertig, dann gespielt, kurz raus und dann waren die Schäden wieder da.

**Comment by Frvetz** [comment]
Alles klar... Ich kümmere mich drum 👍

**Comment by Nordlicht-76** [comment]
Ok...wenn Du noch Infos brauchst, oder ich mal etwas mit Server probieren soll, sag Bescheid... ✌️

**Comment by Frvetz** [comment]
Ist behoben ;) Vielen Dank fürs Melden!

**Comment by Nordlicht-76** [comment]
Moin,
bin gestern zum Ausprobieren gekommen...auch bei mir wieder alles prima 👍 
Danke Dir für den schnellen Fix!
Gruß André
