### ISSUE TITLE
Notification text center screen when closing F1 menu

### ISSUE THREAD

**Issue by Dim67** [Frvetz/FS22_RealisticDamageSystem#22]
I like to play with the F1 menu closed, but then the "tractor needs inspection in 12 months" etc text appears in the top center of my screen. Can you remove that please?
![20240308090956_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/132979972/cd72ab4d-3b55-4730-8582-e444a6dca65c)

**Comment by Frvetz** [comment]
That's from the mod extended input hud and not from mine so I don't have any influence on that.

Without the extended input hud mod the text disappears with closing the F1 menu 👍

**Comment by Dim67** [comment]
Thanks for your reply. I disabled any HUD related mods I have such as Simple Inspector, Production Hud and Extended Input mod, but the line of text still shows only it is now on the left. So, I cant figure out what setting causes this I looked everywhere.

![20240310084425_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/132979972/e3c356c9-b102-49b0-a03e-9ade818245fb)
![20240310084436_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/132979972/8748844e-2361-460c-b259-7758c4c9180f)

**Comment by Dim67** [comment]
Sorry nevermind, found it. Info Message Hud causes this, I overlooked it.

**Comment by Frvetz** [comment]
Oh alright 👍 no worries
