### ISSUE TITLE
Open Maintenance Menu keybind doesn't work with all Valtra brand tractors.

### ISSUE THREAD

**Issue by robpsychobob** [Frvetz/FS22_RealisticDamageSystem#23]
Title says it all. It works with the Q and G series but none of the others.

![Screenshot_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/111586273/97a8945e-1ead-4c01-a259-204b65cfaaba)

**Comment by Frvetz** [comment]
You can change the button in the settings. Its probably because they use the same button. 

Hope this helps :) 

Cheers
Gerrit

**Comment by robpsychobob** [comment]
> You can change the button in the settings. Its probably because they use the same button.
> 
> Hope this helps :)
> 
> Cheers Gerrit

First thing I did was change the button for the Maintenance Menu to Numpad 9 so it wouldn't conflict with any other buttons.
I tested each tractor on it's own.
I tested with no mods installed except RDS.
It also works with all my other vehicles so far.

If there is anything else I can try I'll give it a go.

**Comment by Frvetz** [comment]
So it still doesn't work with the Valtra?

**Comment by robpsychobob** [comment]
The menu would only open with the Valtra G series and Q series tractors. The rest of the Valtra nothing happened when the key was pressed.

**Comment by Frvetz** [comment]
I'll test it later when I get home 👍 thanks in advance for reporting it

**Comment by Frvetz** [comment]
So I did some extended testing now and found no issue. Everything works for me. Are you playing with version 0.9.1.4 (latest)?

**Comment by robpsychobob** [comment]
I downloaded whatever the latest version was the same day I made the bug report. I had just found out about the mod so it was my first download.

I just redownloaded/reinstalled RDS and started a new game on Elm Creek with only the RDS mod installed. I removed all my other mods from the mods folder rather than just deselecting them.

I'm still having the same issue.

I'm also on the Steam version of the game.

Not sure what else to test other than completely reinstalling the game. Lol. Any suggestions?

**Comment by Frvetz** [comment]
Not sure I'm really sorry. I did the exact same thing and had zero issues.

I also don't know why exactly these tractors are causing trouble. The script doesn't work with triggers but calculates the distance to the pallet with the own position and the pallets position so I have no idea why it doesn't work. Either it's because of the steam version or your input is kind of bugged

**Comment by robpsychobob** [comment]
> Not sure I'm really sorry. I did the exact same thing and had zero issues.
> 
> I also don't know why exactly these tractors are causing trouble. The script doesn't work with triggers but calculates the distance to the pallet with the own position and the pallets position so I have no idea why it doesn't work. Either it's because of the steam version or your input is kind of bugged

I was able to fix the problem by just changing the hotkey to another button. I don't know why it worked with some vehicles and not others being bound to Numpad 9, even with no other mods installed, but changing it allowed it work start working.

I guess I didn't think to try that because it was working with other vehicles but I thought one of the first things I tried was setting it back to the default keybind. I probably thought about doing it but then got distracted trying something else.

Either way problem solved.

Thanks for the help though.

**Comment by Frvetz** [comment]
Okay, awesome! No worries! Thanks for reporting it!
