### ISSUE TITLE
Error counting faults and lags/stutter whole game after few minutes...

### ISSUE THREAD

**Issue by FirenzeIT** [Frvetz/FS22_RealisticDamageSystem#24]
Hi, with the latest update 0.9.1.5 there are several errors (I attach screenshots) not in the log, but during the game; also, after a few minutes, the game starts to jerk/laugh too much, becoming unplayable, with v0.9.1.4 this didn't happen.

![1248130_20240403121835_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/113168067/78b67487-54f2-498a-abbc-246b1f99f449)
![1248130_20240403122150_1](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/113168067/6b6dfbe1-4daf-495d-9f44-401bfd0424d9)

**Comment by Frvetz** [comment]
How did you get this amount of damages? Just by playing or with the console command?

**Comment by FirenzeIT** [comment]
by playing, nothing via console.. also with motor off.. I added below a videoclip when countering increase...
ok, in meantime, i continue to use v0.9.1.4..

https://1drv.ms/v/s!AvbOsiDopWJL5lH4HdacpsvQplVB?e=JGRh82

**Comment by Frvetz** [comment]
I'll take a look at it. Thank you!

**Comment by CityFarmerDE** [comment]
Hi, I had the same Issue after updating an existing savegame.  My workarround was. Load savegame, Open the settings Menu, adjust some RealisticDamageSystem Settings, save Game. After that I could enter vehicles without endless counting faults.

**Comment by FirenzeIT** [comment]
I also tested without save any game.. So, it's need mandatory save game
etc? Because for works without any problems, this workaround it's need only
temporary..

Il Mer 3 Apr 2024, 16:47 CityFarmerDE ***@***.***> ha scritto:

**Comment by Frvetz** [comment]
I found the problem. Thank you two for reporting it!! I'll update the file on GitHub in the next few hours

**Comment by foreverls19** [comment]
Hallo,
bei mir werden die Schäden auch hoch gezählt, neuste Version und neuen Spielstand

**Comment by Frvetz** [comment]
Könntest du bitte die Log Datei anfügen, nachdem der Fehler aufgetreten ist, um mir bei der Fehlersuche zu helfen 😃 Die Datei findest du unter Dokumente -> My Games -> Farming Simulator 22 -> Log.txt

Danke dir 🙂

**Comment by foreverls19** [comment]
der Fehler tritt sofort auf, sobald ich in ein Fahrzeug steige.
[log.txt](https://github.com/Frvetz/FS22_RealisticDamageSystem/files/14920180/log.txt)

**Comment by Frvetz** [comment]
Alles klar, der Fehler tritt wahrscheinlich auf, weil du einmal mit der Version 0.9.1.4 gespeichert hast und jetzt der falsche Wert im Savegame gespeichert ist. Um den Fehler zu beheben kannst du einfach das Spiel starten und ohne in ein Fahrzeug zu steigen alle Einstellungen eine Stufe ver- und wieder zurückstellen. Dann sollte wieder alles funktionieren 🙂 👍 aber trotzdem danke fürs Melden!

**Comment by foreverls19** [comment]
war zwar ein neues Savegame, versuche es aber trotzdem mal

**Comment by Frvetz** [comment]
stimmt... Dann weiß ich erstmal auch nicht weiter. Das Problem gab es in Version 0.9.1.4 und da hatte ich es mit einem neuen Savegame selbst auch.. Aber das konnte ich beheben

**Comment by foreverls19** [comment]
habe jetzt ein neues Savegame gestartet, deine Anweisungen befolgt, siehe da
es geht.:-)
Teste es nun mal auf meinem Server

**Comment by foreverls19** [comment]
habe es nun auf dem Server getestet, 
Problem ist, dass sich die Einstellungen nicht speichern lassen, sobald ich wieder ins Spiel geh sind die alten Daten wieder drin

**Comment by Frvetz** [comment]
Ohh okay... Ich teste das selbst mal und versuche es zu beheben, wenn ich den Fehler reproduzieren kann. Danke fürs Melden! Ich öffne auch direkt einen neuen Issue damit die Fehler getrennt bleiben

**Comment by Frvetz** [comment]
@foreverls19 Ich schreibe es hier auch nochmal: 
Ich konnte auf dem Dedi keine Probleme feststellen... Die Werte werden bei mir sauber gespeichert und sind nach Neustart immer noch vorhanden 🤷‍♂️
