### ISSUE TITLE
No damages

### ISSUE THREAD

**Issue by Frvetz** [Frvetz/FS22_RealisticDamageSystem#26]
Waiting for further tests/information from @Merrlin

**Comment by Merrlin** [comment]
Sounds good to me… As for now rdsDebug shows that the next known and unknown damages are 2hrs(InGame), or something like that, in the Future. So I should reach the time marks on the upcoming weekend.

But maybe I reseted the damage counter accidentally with the last (unnecessary) Inspection.

so, as for now it’s more like a MayBeBug 😁

**Comment by Frvetz** [comment]
Alright 😁

**Comment by Frvetz** [comment]
I'll close this for now :D
