### ISSUE TITLE
Feature Request Display extension

### ISSUE THREAD

**Issue by djdanby** [Frvetz/FS22_RealisticDamageSystem#27]
Vehicle display output as with Dashboard Live or Ifkos Display Script.

I would like to be able to display the problems of the vehicle in a dashboard. This would be a great addition to the Dashboard Live script. 
You could add a maintenance menu to the vehicle display menus and display any vehicle error messages or vehicle problems in the internal vehicle dashboard.

Most tractors in realism have such menus where you can see various wear and tear or faults. Or you can also see when an inspection is necessary. This would therefore be a great addition to the mod.

For example, you could display it in text form or as icons on the display in the vehicle. Although both options would be great at the same time. Then you could customize your design as you like. :)

That would be really nice :)

PS: Very cool mod. Thumps up!

**Comment by jason0611** [comment]
Please wait for the next Dashboard Live Update, which supports RealisticDamageSystem. Then modders could add this function to their vehicles.

**Comment by Frvetz** [comment]
Thank you! Exactly. @jason0611, the creator of dashboard live, already integrated it :) you can check out the dashboard live github version if you want to

**Comment by djdanby** [comment]
Ah ok. Thanks for the Info :)
