### ISSUE TITLE
no vehicles appearing in menu

### ISSUE THREAD

**Issue by JamesTM2070** [Frvetz/FS22_RealisticDamageSystem#28]
when opening the RVB menu no vehicles appear in the "vehicle overview" tab. Please see attached image
![no vehicle](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/89275757/30450646-166a-42ee-8f24-8a1a99c32486)

**Comment by Frvetz** [comment]
Hello, 

that window is not from my script but from the "Real Vehicle Breakdowns" script (https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA)

From what I can see in his GitHub repository there a quite a lot of bugs and he doesn't respond to all of them so yeah, I don't know. At least you could try to create an issue there and hope that he will fix this bug in the future.

My script uses a pallet available in the shop. Just buy it, drive up to it and open my menu there (if you play with my script and didn't just click on the wrong GitHub repository :D ) You can read through my desciption and tutorial [here ](https://github.com/Frvetz/FS22_RealisticDamageSystem/blob/main-tested-beta/README.md#english-description-%EF%B8%8F-hier-findest-du-die-deutsche-bescheibung) if you want.

Hope I could help

Cheers
