### ISSUE TITLE
Issue with incorrect repair time information and damage meter

### ISSUE THREAD

**Issue by bojanh66** [Frvetz/FS22_RealisticDamageSystem#3]
First of all, thank you for great damage mod.
I have found 2 issues.
Lets say i started maintenance at 10:00 and it will be finished at 15:16.
I slowly fast forward time until 15:16, but its not finished, so i have to wait until next day 15:16...is it a bug or a feature? It should be explained better in F1 info window that it will be finished next day, not current day.

Then another issue i have found is repair doesnt always fix vehicle until 100%.
I did multiple inspections and there is 0 damage, but damage bar of vehicle is still not at 0%.
I have to sleep 1-2 days (or months depending how you call it), then to do inspection, 1 damage will be found, i will fix it and only then damage meter is totally fixed.

These are 2 issues i have found so far.
![fsScreen_2024_01_15_21_30_47](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/32069662/17c52603-30bc-4f7f-b77c-c83c510627e7)
![fsScreen_2024_01_15_21_42_42](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/32069662/edcab55a-8a3b-4fa2-8142-3c0266d255c7)

**Comment by Frvetz** [comment]
Thank you for your review!

1. If the maintenance has to be paused it will be displayed multiple times when starting it. If there is no text that says that it needs to be paused then it is a bug. 

2. This shouldn't be 🤔 how long have you been playing with the mod?

**Comment by Frvetz** [comment]
-- switched to discord --
