### ISSUE TITLE
engine start temperature

### ISSUE THREAD

**Issue by DrewCZ** [Frvetz/FS22_RealisticDamageSystem#30]
Hey hey, @Frvetz please consider that if possible to set the start engine temperature according to the environment temperature. Because start at i.e. 21°C is more realistic and will be better than 1°C in mid summer :) 
thank you, love your mod! 
drewCZ aka ticho

**Comment by Frvetz** [comment]
Hey! Thanks so much for the idea!

I'm not sure if you have confused a function of the CVT mod with mine, but the engine warm-up function is from the CVT_Addon and not from me. The idea is great, but not relevant for my mod or the game without the CVT_addon 😅 however I know the CVT creator and would pass the idea on to him if you meant his function?

Of course I could add the function to my mod anyway, but then other players would have to play with my mod to be able to use this function as well.

Cheers
Gerrit/Frvetz

**Comment by DrewCZ** [comment]
oh, sorry, it's caused by https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/

**Comment by Frvetz** [comment]
No worries :D just open a new issue on his GitHub. Unfortunately I don't have any contact to him since he wasn't very cooperative when asking about working together but you can definitely ask for that feature!
