### ISSUE TITLE
Feature request: Have number of hours until completion

### ISSUE THREAD

**Issue by GodAtum360** [Frvetz/FS22_RealisticDamageSystem#5]
Sometimes it's a bit confusing if the repair takes a number of days and I loose track of how many days are left. It would be nice to have a countdown of the number of hours left alongside the time to completion.

**Comment by Frvetz** [comment]
Added a text for the days in the new update! :D 

New version with a lot of other new features and fixes is online here now. Thanks for your Idea!!
