### ISSUE TITLE
Can't move the machine after repairs

### ISSUE THREAD

**Issue by goldenshoes** [Frvetz/FS22_RealisticDamageSystem#7]
Hi,

Just did repairs on two machines and once repairs are done I can't move it unless I reload the game. Log file is clear

**Comment by Frvetz** [comment]
Hi!

Thank you for letting know!!! I uploaded a fix just now!

Best regards
Gerrit / frvetz

goldenshoes ***@***.***> schrieb am Sa. 3. Feb. 2024 um 23:59:
