### ISSUE TITLE
Vanilla Schadensanzeige zeigt weiterhin Schäden

### ISSUE THREAD

**Issue by MeRida2104** [Frvetz/FS22_RealisticDamageSystem#8]
Hi @Frvetz , 

ich habe heute früh deine neuste Version eingesetzt, weil wir vom ersten Changelog Punkt betroffen waren. 

Es ist uns kürzlich aufgefallen (ich bin mir nicht sicher, ob das bereits zuvor der Fall war), dass die Standard-Schadensanzeige weiterhin Schäden am Fahrzeug anzeigt, selbst nachdem das Fahrzeug repariert wurde und auch die Inspektion keine Schäden aufgezeigt hat (aus Einfachheitsgründen wurde dies mittels "rdsFindDamages" über die Konsole durchgeführt).

![image](https://github.com/Frvetz/FS22_RealisticDamageSystem/assets/96819380/bec00d63-299b-40df-98bf-486d7f6fa5fa)

Feature oder Bug? :-)

 Beste Grüße
 MeRida

**Comment by Frvetz** [comment]
Hey MeRida,
das ist komisch... Ich schaue nachher noch mal in das Skript und melde mich dann hier nochmal.

Der Schaden sollte auf jeden Fall komplett verschwinden wenn du einen Schaden reparierst. (Konsolenbefehl "rdsRemoveDamages -1", um einen Schaden hinzuzufügen und dann "rdsRemoveDamages 1", um diesen wieder zu reparieren)

Danke fürs Melden!!

Beste Grüße
Gerrit / frvetz

**Comment by MeRida2104** [comment]
Mit dem Befehl konnte ich alles sauber nachspielen. 3 Schäden hinzugefügt, 3 Schäden entfernt: Schaden 0%.

**Comment by Frvetz** [comment]
Wunderbar, ich konnte das Problem jetzt in meinen Tests nicht reproduzieren... Ich gehe mal davon aus, dass der Schaden also schon davor so war und nur eine neue Reparatur gebraucht hat, um wieder richtig angezeigt zu werden.

Ich schließe den Issue dann hier :)

Aber dennoch Danke für deine Mühe!

Beste Grüße
Gerrit / frvetz

**Comment by MeRida2104** [comment]
Immer gerne :) Wir beobachten das ein wenig weiter.

**Comment by Andre-76** [comment]
Moin, habe das Phänomen bei mir auch. Reparatur abgeschlossen, aber Vanilla Anzeige fast unten. Werde nachher mal mit Konsole reparieren und auch weiter beobachten.

**Comment by Frvetz** [comment]
🤔 dann mache ich den Issue wieder auf... Ich schaue auch nochmal

**Comment by Frvetz** [comment]
Bei mir funktioniert es... Version 0.9.1.1

Inspektion durch... 8 Schäden... Nach der Reparatur kein Standardschaden mehr vorhanden

**Comment by Andre-76** [comment]
Hatte heute morgen auch die neue Version eingespielt, dem aber noch keine weitere Beachtung geschenkt, da ja den Server während der Reparatur neu gestartet. Wollte das weiter beobachten und dann über den Beitrag hier gestolpert. Ich will aber einen anderen Mod nicht ausschließen. Muss nachher @home mal schauen, ob da nicht ein anderer mit Reinspielen könnte.

**Comment by Andre-76** [comment]
Ich konnte es jetzt auch nicht wirklich reproduzieren, hab mir aber mal den Spielstand vom Server gezogen. 
Wenn ich im Fahrzeug das Reparaturmenü aufrufe, gibt es nichts zu reparieren. Eine Inspektion  findet auch keine Schäden. 
Mit dem Befehl "rdsResetDamages" wird der Balken wieder gesund grün ;)

In der vehicels.xml habe ich nur einen kleinen Unterschied beim Vanilla-Schaden gefunden (ich glaube der Eintrag bedeutet es)

XML-Teil Fahrzeug mit "Fehler"
```
<wearable damage="0.832176">
  <wearNode amount="1.000000"/>
</wearable>

<RealisticDamageSystem NextInspectionAge="20" DamagesThatAddedWear="0" FinishDay="21" FinishHour="8" FinishMinute="3" DialogSelectedOptionCallback="0" NextKnownDamageAge="14" NextUnknownDamageAge="11" TotalNumberOfDamagesPlayerKnows="0" TotalNumberOfDamagesPlayerDoesntKnow="0" NextKnownDamageOperatingHour="29.700001" NextUnknownDamageOperatingHour="37.599998" FirstLoadNumbersSet="true" MaintenanceActive="false" InspectionActive="false" CVTRepairActive="false" LengthForDamages=""/>
```

```
XML-Teil Fahrzeug nach "rdsResetDamages"
<wearable damage="0.000000">
  <wearNode amount="1.000000"/>
</wearable>

<RealisticDamageSystem NextInspectionAge="20" DamagesThatAddedWear="0" FinishDay="21" FinishHour="12" FinishMinute="0" DialogSelectedOptionCallback="0" NextKnownDamageAge="14" NextUnknownDamageAge="11" TotalNumberOfDamagesPlayerKnows="0" TotalNumberOfDamagesPlayerDoesntKnow="0" NextKnownDamageOperatingHour="29.700001" NextUnknownDamageOperatingHour="37.599998" FirstLoadNumbersSet="true" MaintenanceActive="false" InspectionActive="false" CVTRepairActive="false" LengthForDamages=""/>
```

Ich hoffe, ich deute es richtig ;)
Reine Vermutung jetzt...nicht während der Reparatur updaten oder Server neu starten...da muß wohl was durcheinander gekommen sein  😆

**Comment by Frvetz** [comment]
Alles klar! Ja das kann sein... 

Zur Info: Der Schadensbalken wird nicht durchgehend geupdated, damit auch andere Scripte noch Standardschaden hinzufügen/abziehen können. Bei jedem neuen Schaden wird Standardschaden hinzugefügt und bei jeder Reparatur proportional zu den insgesamten RDS-Schäden abgezogen. Sprich wenn man nur einen Schaden zum Reparieren, aber 80% Standardschaden hat, dann wird bei der Reparatur von dem einen Schaden trotzdem -80% gerechnet.

Ich schließe den Issue an der Stelle wieder 👍 aber Danke für's Melden!

Beste Grüße
Gerrit / frvetz
