### ISSUE TITLE
[Feature Request] Adjust Workshop Hours

### ISSUE THREAD

**Issue by MeRida2104** [Frvetz/FS22_RealisticDamageSystem#9]
Would it be possible to add a feature allowing me to set the opening and closing times of the workshop?

**Comment by Frvetz** [comment]
It would theoretically be possible, but I have to say that it is quite a lot of work, as all the texts have to be changed as well. But I'll make a note of it and have a look when I find the time :D

**Comment by Frvetz** [comment]
Now you can choose your own workshop times in the game settings 🙂 (aber weißt du ja schon ^^)
https://github.com/Frvetz/FS22_RealisticDamageSystem/releases/latest
